import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@repo/ui/globals.css";
import { Toaster } from "@repo/ui/components/ui/toaster";
import Providers from "./shared/Provider";
import SideNav from "./shared/SideNav";
import { cn } from "@repo/ui/lib/utils";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <main className="min-h-screen w-full bg-white text-black flex">
        <Providers>
          <SideNav />
          <div className="p-8 w-full">{children}</div>
        </Providers>
      
        </main>
        <Toaster />
      </body>
    </html>
  );
}
